### ISSUE TITLE
Syntax highlighing 

### ISSUE THREAD

**Issue by melmasri** [fniessen/refcard-org-mode#1]
Hello,
I am trying your BigBlow and ReadTheOrg, they are amazing. I am trying to use them in some projects.
However, I can't get the code syntax highlighting to work. I download the refcard-org-mode reademe and complied it, everything works except the syntax highlighting. I am using Debain Linux with Emacs 24 and Org-mode > 8. Should I install something? I can't get it to work.

Thanks

**Comment by fniessen** [comment]
I do have

```
;; Output type to be used by htmlize when formatting code snippets
(setq org-html-htmlize-output-type 'css)
```

and, for sure, htmlize.el (found in org-contrib) must be in your `load-path`. Is this the case?

**Comment by melmasri** [comment]
Ok yes, it works. All I had to do is  `apt-get install emacs-goodies-el`. I am usingLinux Debian and apparently `htmlize.el` is included in the package `emacs-goodies-el`. 

Ok great, the theme is amazing. Thanks for the help.

I think it would be good to add this information to the readme, new users of emacs might not know about it.

**Comment by fniessen** [comment]
Good to know!  Thx.
